# Generated by Django 5.2.7 on 2025-11-08 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingTickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingrecord',
            name='total_charge',
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='hours_parked',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingrecord',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
