# Generated by Django 5.2.7 on 2025-11-08 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingTickets', '0002_remove_parkingrecord_total_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('credit_card', 'Credit Card'), ('mall_code', 'Mall Code')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('parking_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ParkingTickets.parkingrecord')),
            ],
        ),
    ]
