# Generated by Django 5.2.7 on 2025-11-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingTickets', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
