# Generated by Django 5.2.7 on 2025-11-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingTickets', '0004_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
